name: Daily Weather Check

on:
  schedule:
    - cron: '16 2 * * *'  # UTC 2:15 (日本時間 11:15) に実行
  workflow_dispatch:  # 手動トリガーも追加（オプション）

jobs:
  check_weather:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up environment variables
      run: echo "LINE_NOTIFY_TOKEN=${{ secrets.LINE_NOTIFY_TOKEN }}" >> $GITHUB_ENV

    - name: Run weather check script
      run: |
        python check_weather.py > check_weather.log 2>&1

    - name: Upload log file
      uses: actions/upload-artifact@v3
      with:
        name: weather-log
        path: check_weather.log
